# Generated by Django 6.0.6 on 2026-09-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_index', '0010_rdn2008_srid'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='s3_key_filter_regex',
            field=models.CharField(blank=True, help_text='Optional regex (re.search, applied to the full S3 object key) further restricting which objects under s3_prefix are indexed for this camera. Leave blank to index every object under the prefix.', max_length=255, null=True),
        ),
    ]
